[workspace]
resolver = "2"
members = [".", "python", "server"]

[package]
name = "melosim"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
anymap2 = "0.13"
mujoco-rs = { version = "5", features = ["auto-download-mujoco"] }
