[workspace]
resolver = "2"
members = ["."]

[package]
name = "melosim"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
mujoco-rs = { version = "5", features = [
  "auto-download-mujoco",
], optional = true }
bevy = { version = "0.19.0", features = ["bevy_dev_tools", "free_camera"] }
bevy_dev_tools = "0.19.0"
nalgebra = { version = "0.35", features = ["convert-glam032"] }

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[features]
default = ["mujoco"]
mujoco = ["dep:mujoco-rs"]
